/* eslint-disable no-dupe-keys */
import { StyleSheet, Dimensions } from "react-native";
import Theme from "../../Utils/Theme";

const styles = StyleSheet.create({
  MainView: {
    flex: 1,
  },
  header: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#333333",
    shadowOffset: { width: -1, height: -3 },
    shadowRadius: 2,
    shadowOpacity: 0.4,
    // elevation: 5,
    paddingTop: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  panelHeader: {
    alignItems: "center",
  },

  panelButton: {
    padding: 13,
    borderRadius: 10,
    backgroundColor: Theme.primary,
    alignSelf: "center",
    marginVertical: 7,
    alignItems: "center",
    position: "absolute",
    width: "70%",
    bottom: 0,
  },
  picVoiceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    bottom: Theme.hp("1.6%"),
    alignSelf: "center",
    paddingHorizontal: Theme.wp("1%"),
  },
  picVoiceWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    paddingHorizontal: Theme.wp("2%"),
    borderRadius: 7,
    borderColor: "#66B5EB",
    backgroundColor: "#fff",
    ...Theme.shadow,
  },
  txtAdd: {
    color: Theme.primary,
    marginRight: 4,
    fontSize: Theme.RFPercentage(1.3),
    fontWeight: "bold",
  },
  wrapPlusBtn: {
    backgroundColor: Theme.primary,
    width: Theme.wp("15%"),
    height: Theme.wp("15%"),
    borderRadius: 90,
    alignItems: Theme.align,
    justifyContent: Theme.align,
    position: "absolute",
    bottom: "25%",
    right: "5%",
  },
  mapTypeContainer: {
    flexDirection: "row",
    marginTop: Theme.hp("1%"),
    justifyContent: "space-evenly",
  },
  mapTypeIcon: {
    backgroundColor: Theme.white,
    width: Theme.wp("10%"),
    height: Theme.wp("10%"),
    borderRadius: 20,
    alignItems: Theme.align,
    justifyContent: Theme.align,
    position: "absolute",
    top: "5%",
    right: "5%",
    borderWidth: 0.3,
    borderColor: Theme.primary,
  },
  mapType: {
    height: Theme.hp("10%"),
    width: Theme.wp("20%"),
    alignItems: "center",
    borderRadius: 15,
    borderWidth: 3,
    ...Theme.shadow,
  },
  header: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#333333",
    shadowOffset: { width: -1, height: -3 },
    shadowRadius: 2,
    shadowOpacity: 0.4,
    // elevation: 5,
    paddingTop: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  panel: {
    backgroundColor: "#fff",
    padding: "3%",
    height: Theme.hp("58%"),
  },
  imgMarker: {
    width: Theme.wp("5%"),
    height: Theme.hp("2.5%"),
    marginTop: Theme.hp("0.7%"),
    marginLeft: Theme.wp("3%"),
  },
  txtTitle: {
    fontSize: Theme.RFPercentage(2.6),
    color: "#000000",
    fontWeight: "bold",
  },
  txtAddress: {
    fontSize: Theme.RFPercentage(2),
    color: "#000000",
    fontWeight: "bold",
    // marginTop: Theme.hp("1%"),
  },
  txtCreatedBy: {
    fontSize: 20,
    fontWeight: "600",
  },
  txtPosts: {
    // color: '#959494',
    color: "white",
    fontSize: 16,
    fontWeight: "500",
    marginTop: "5%",
  },
  // modalWrapper: {
  //   backgroundColor: 'white',
  //   borderRadius: 30,
  //   elevation: 4,
  //   height: '10%',
  //   marginTop: '15%',
  // },
  heading: {
    top: 20,
    color: "black",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  boxWrap: {
    backgroundColor: "rgba(33, 150, 243, 0.5)",
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: Theme.hp("1%"),
    paddingLeft: Theme.wp("3%"),
    paddingRight: Theme.wp("4%"),
    borderRadius: 5,
  },
  txtStatus: {
    color: Theme.black,
    fontWeight: "600",
    fontSize: 16,
  },
  ImgPin: {
    height: 20,
    width: 20,
    position: "absolute",
    right: 1,
  },
  btnNavigate: {
    alignItems: "center",
    justifyContent: "center",
    height: "15%",
    width: "100%",
    backgroundColor: "#1596F3",
    borderRadius: 5,
    bottom: 5,
    // marginTop: Theme.hp("2.5%"),
  },
  txtNavigate: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: Theme.RFPercentage(2.4),
  },
  addpostBtn: {
    alignSelf: "flex-start",
    fontSize: 20,
    marginTop: 10,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#1596F3",
    backgroundColor: Theme.primary,
    padding: 7,
    marginBottom: 20,
    elevation: 3,
    width: "42%",
    color: "#1596F3",
  },
  cancelBtn: {
    alignSelf: "flex-start",
    fontSize: 20,
    marginTop: 10,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#1596F3",
    backgroundColor: Theme.white,
    padding: 7,
    marginBottom: 20,
    elevation: 3,
    width: "42%",
  },
  addquiz: {
    alignSelf: "flex-start",
    fontSize: 20,
    marginTop: 10,

    padding: 7,
    color: "#1596F3",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    marginRight: Theme.wp("4%"),
    // marginHorizontal: Theme.wp("8%"),
  },
  option: {
    color: "black",
    alignSelf: "flex-start",
    fontSize: 17,
  },
  markerin: {
    width: "100%",
    height: 100,
    color: "white",
    fontSize: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e1e1e1",
    backgroundColor: "#66B5EB",
    marginBottom: 17,
    textAlignVertical: "top",
  },
  heading2: {
    color: "black",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: "4%",
  },
  markerTxin: {
    width: "100%",
    color: "white",
    fontSize: 16,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#e1e1e1",
    backgroundColor: "#66B5EB",
    marginBottom: 17,
  },
  modalWrapper: {
    backgroundColor: "white",
    borderRadius: 15,
    // marginTop: "15%",
  },
  arrivedBtn: {
    alignSelf: "center",

    marginTop: 10,
    marginBottom: 20,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#1596F3",
    backgroundColor: Theme.primary,

    padding: 7,
    marginTop: 20,
    elevation: 3,
    // width: '42%',
    color: "#1596F3",
  },
  value: {
    fontSize: 17,
    color: "red",
    marginRight: Theme.wp("4%"),
  },
  headingName: {
    alignSelf: "flex-start",
    marginTop: "10%",
    marginBottom: "3%",
    color: "black",
    fontSize: 20,
    fontWeight: "bold",
  },
  crossButton: {
    // padding: 13,
    margin: 20,
    borderRadius: 10,
    backgroundColor: Theme.primary,
    alignSelf: "flex-end",
    marginVertical: 7,
    alignItems: "center",
  },
  panelButtonTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "white",
  },
  photoBorder: {
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    height: Theme.hp("25%"),
    width: Theme.wp("75%"),
    borderWidth: 2,
    borderRadius: 20,
    borderColor: Theme.primary,
  },
  imgEdit: {
    height: Theme.hp("25%"),
    width: Theme.wp("75%"),
    resizeMode: "cover",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: Theme.primary,
  },
});

export default styles;
