const Language = {
  titleWelcome: 'Welcome to Scavenger!',
  titleScavenger: 'Welcome to Scavenger Support!',
  descScavengerSupport:
    'Thanks for your interest in our support! By using our support, you can get help.',

  descWelcome:
    'Thanks for your interest in our assessment services! By using our Services, you agree to the Agreement.',
  titleAccess: 'Access to the Services, Scavenger Accounts.',
  descAccess:
    'Your use of the Services is subject to your creation and our approval of Scavenger account (an Account). We have the right to refuse or limit your access to the Services. By submitting your registration to use our assessment and other Services, if you are an individual. You may only have one Account. By enrolling in Scavenger, you permit Scavenger to serve, as applicable, Scavenger has right to refuse to provide services to any assessment services under certain circumstances or business reasons thereof.',
  titleServices: 'Using our Services',
  descServices:
    "You may use our Services only as permitted by this Agreement and any applicable laws. Don't misuse our Services. For example, don't interfere with our Services, APIs or try to access them using a method other than the interface and the instructions that we provide.",
  titleChangeServices: 'Changes to our Services; Changes to the Agreement',
  descChangeServices:
    "We are constantly changing and improving our Services. We may add or remove functionalities or features of the Services at any time, and we may suspend or stop a service altogether. We may modify the Agreement at any time. We'll post any modifications to the Terms of Use on this page and any modifications to the Privacy. If you don't agree to any modified terms in the Agreement, you'll have to stop using the affected Services.",
  titleIntellectual: 'Intellectual Property',
  descIntellectual:
    "Other than as set out expressly in the Agreement, neither party will acquire any right, title or interest in any intellectualproperty rights belonging to the other party or to the other party's licensors. If Scavenger provides you with software or Application as a service in connection with the Services, we grant you a non-exclusive, non-sub licensable license for use of such software or Application. This license is for the sole purpose of enabling you to use and enjoy the benefit of the Services as provided by Scavenger. You may not copy, modify, distribute, sell, or lease any part of our Services or included software or Application, nor may you reverse engineer or attempt to extract the source code of that software, unless you have our written permission from Scavenger. You will not remove, obscure, or alter Scavenger copyright notice, Brand Features, or other proprietary rights notices affixed to or contained within any Scavenger services, software, Application or documentation.",
  titlePrivacy: 'Privacy',
  descPrivacy:
    "Your privacy is important at Scavenger, so we've developed a Privacy Policy that covers how we collect, use, disclose,transfer, and store your information. Please take a moment to  familiarize yourself with our privacy practices and contact if you have any question. Collection and Use of Personal information data that can be used to uniquely identify or contact a single person. You are asked to provide your personal information to sign Up at Scavenger. Here are some examples of the types of personal information Scavenger may collect and how we may use it. The  personal information we collect allows us to keep you posted on Scavenger latest product announcements, updates, and upcoming events. It also helps us to improve our services and content. We also use personal information to help us develop, deliver, and improve our products, services and content. We may also use personal information for internal purposes such as auditing, data analysis, and research to improve Scavenger products, services, and customer communications.",
  titleIntegrity: 'Integrity and Retention of Personal Information.',
  descIntegrity:
    'Scavenger makes it easy for you to keep your personal information accurate, complete, and up to date. We will retain your personal information for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted by law. Our Companywide Commitment to Your Privacy To make sure your personal information is secure, we communicate our privacy and security guidelines to Scavenger employees and strictly enforce privacy safeguards within the company by an email or updates by email of any change in the privacy policy.',
  titleRefund: 'Refund and Cancellation Policy',
  descRefund:
    'If you make any payment to buy detailed report using www.Scavenger.com, the money can not be refunded. No cancellation is possible once you have made the payment. Once the payment is made it is not transferable to any other candidate.',
  titleConfidentiality: 'Confidentiality',
  descConfidentiality:
    "You agree not to disclose Scavenger Confidential Information without our prior written consent.  OTHER THAN AS EXPRESSLY SET OUT IN THE AGREEMENT, WE DO NOT MAKE ANY PROMISES ABOUT THE SERVICES. FOR EXAMPLE, WE DON'T MAKE ANY COMMITMENTS ABOUT THE CONTENT WITHIN THE SERVICES, THE SPECIFIC FUNCTION OF THE SERVICES, OR THEIR PROFITABILITY, RELIABILITY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS. WE PROVIDE EACH SERVICE AS IS. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES, EXPRESS, STATUTORY OR IMPLIED. WE EXPRESSLY DISCLAIM THE WARRANTIES OR CONDITIONS OF NONINFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.,Your privacy is important at Scavenger, So we've developed a Privacy Policy that covers how we collect, use, disclose, transfer, and store your information. Please take a moment to familiarize yourself with our privacy practices and contact if you have any questions. Collection and Use of Personal information data that can be used to uniquely identify or contact a single person. You are asked to provide your personal information to sign Up at Scavenger. Here are some examples of the types of  personal information Scavenger may collect and how we may use it",
  titlePersonalInfo: 'How we use your personal information',
  descPersonalInfo:
    "The personal information we collect allows us to keep you posted on Scavenger's latest product announcements, updates, and upcoming events. It also helps us to improve our services and content. We also use personal information to help us develop, deliver, and improve our products, services, and content. We may also use personal information for internal purposes such as auditing, data analysis, and research to improve Scavenger products, services, and customer communications. Disclosure to Third Parties that Scavenger partners for conducting assessments for them and Scavenger may make certain personal information available of the user or users provided by that customer to access the report, result, or any data that may be used for recruitment, development, certification or any other similar insight. For example, when you subscribe and activate your Scavenger account, you authorize Scavenger and its carrier to exchange the information you provide during the activation process to carry out the delivery service. If you are approved for service, your account will be governed by Scavenger and its delivery partners' respective privacy policies. Personal information will only be shared by Scavenger to provide or improve our products and services. It will not be shared with third parties for their marketing purposes. It may be necessary by law, legal process, litigation, and/or requests from public and  governmental authorities within or outside your country of residence - for Scavenger to disclose your personal information. We may also disclose information about you if we determine that for purposes of national security, law enforcement, or other issues of public importance, disclosure is necessary or appropriate. Protection of Personal Information Scavenger takes precautions - including administrative, technical, and physical measures - to safeguard your personal information against loss, theft, and misuse, as well as against unauthorized access,  disclosure, alteration, and destruction.",
  titleRetention: 'Integrity and Retention of Personal Information',
  descRetention:
    'Scavenger makes it easy for you to keep your personal information accurate, complete, and up to date. We will retain your personal information for the period necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted by law. Our Companywide Commitment to Your Privacy To make sure your personal information is secure, we communicate our privacy and security guidelines to Scavenger employees and strictly enforce privacy safeguards within the company by email or updates by email of any change in the privacy policy.',
  titleCollection: 'Collection and use of your personal information',
  descCollection:
    'The remote proctoring solution may have the requirement to collect images or information from you while offering distributed assessment services. With regard to security, Personal Information from you while offering assessment services due to the nature of the conducting secured and proctored assessment services being offered. SPDI shall have the meaning in accordance with the Information Technology (Reasonable security practices and procedures and sensitive personal data or Information), With  regard to security, we respect all information provided to us, and take all reasonable steps towards protection of the same. We have implemented technology and policies, with the objective of protecting your privacy from unauthorized access and improper use, and periodically review the same. We maintain procedural safeguards to protect the confidentiality and security of personally identifiable information transmitted to us.',
  titleLaws: 'Laws specific to India',
  descLaws:
    'In the case where Scavenger is an intermediary between the client and consumer. Whereas a client herein is the agency that assigns work to Scavenger to collect personal while registration for conducting an assessment on behalf of the client for a certain test or a series of tests for a specific role or roles to be used for client’s requirement. Under Section 79 of the IT Act, intermediaries are exempt from liability under the Act in respect of any third-party information, data, or communication link made available or hosted by them. The storage and purge policy of the data, information, or processing to be directed by the client. Clients are hereby supposed to store data temporarily or permanently based on requirements and Scavenger is not liable for storing data indefinitely for any client or assessment.',
  titlePrivacyQue: 'Privacy Questions',
  descPrivacyQue:
    'If you have questions or concerns about Scavenger Privacy Policy or data processing, please contact us at info@Scavenger.com.',
};
export default Language;
